# ============================================================
# Backup Control — Portainer Stack (GitHub deployment)
# ============================================================
# Image is built automatically by GitHub Actions and pushed
# to GitHub Container Registry (ghcr.io).
#
# IMPORTANT: After deploying, edit the stack in Portainer UI
# to adjust the volume paths below to match YOUR server.
# ============================================================

services:
  backup-control:
    image: ghcr.io/artem-levchenko-2/backup-control:latest
    container_name: backup-control
    restart: unless-stopped
    ports:
      - "3100:3000"
    volumes:
      # Persistent SQLite database
      - backup-control-data:/app/data

      # ── CUSTOMIZE THESE PATHS IN PORTAINER STACK EDITOR ──
      # Rclone config (change left side to YOUR rclone config path)
      - /home/artem/.config/rclone/rclone.conf:/etc/rclone/rclone.conf:ro

      # Host storage directories (read-only for backup source access + disk stats)
      - /srv/storage:/srv/storage:ro
      - /mnt:/mnt:ro

    environment:
      - NODE_ENV=production
      - RCLONE_CONFIG=/etc/rclone/rclone.conf

volumes:
  backup-control-data:
    driver: local
