# ============================================================
# Backup Control — Portainer Stack (GitHub deployment)
# ============================================================
# Image збирається автоматично через GitHub Actions → GHCR
# rclone конфіг та дані монтуються з хостової системи
# ============================================================

services:
  backup-control:
    image: ghcr.io/artem-levchenko-2/backup-control:latest
    container_name: backup-control
    restart: unless-stopped
    ports:
      - "3100:3000"
    volumes:
      # Persistent SQLite database
      - backup-control-data:/app/data
      # rclone config from host
      - /home/artem/.config/rclone:/root/.config/rclone:ro
      # Source data directories (read-only)
      - /mnt/toshiba:/mnt/toshiba:ro
      - /srv/storage/transcend:/srv/storage/transcend:ro
      - /srv/storage/media:/srv/storage/media:ro
      - /srv/storage:/srv/storage:ro
      # Logs
      - backup-control-logs:/app/logs
    environment:
      - NODE_ENV=production
      - RCLONE_CONFIG=/root/.config/rclone/rclone.conf

volumes:
  backup-control-data:
    driver: local
  backup-control-logs:
    driver: local
